checkpoint: (any_checkpoint_model).safetensors
image-size:
  height: 1024
  width: 1024
lora:
- enabled: false
  model: (any_lora_model).safetensors
  strength: 1.0
  trigger: 
sampling:
  cfg: 5
  steps: 24
vpred: false
