checkpoint: catTowerNoobaiXL_v17Vpred.safetensors
image-size:
  height: 1024
  width: 1024
lora:
- enabled: false
  model: lora-ix-koto_nai3-v1.safetensors
  strength: 0
  trigger: koto_nai3
sampling:
  cfg: 5
  steps: 24
vpred: true
